name: sembast
description: A simple io database
dev_dependencies:
  idb_shim: any
  tekartik_test:
    git: git://github.com/alextekartik/tekartik_test.dart
dependency_overrides:
  idb_shim:
    path: ../idb_shim.dart
