name: sembast
version: 1.9.1
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: Simple embedded file system database
homepage: https://github.com/tekartik/sembast.dart
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  logging: '>=0.11.3'
  path: '>=1.5.1'
  synchronized: '>=1.5.1'
  dart2_constant: '>=1.0.1'

dev_dependencies:
  test: '^1.0.0'
  dev_test: '>=0.1.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
  browser: any
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
