name: sembast
version: 1.3.6
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: Simple embedded file system database
homepage: https://github.com/tekartik/sembast.dart
environment:
  sdk: '>=1.19.1 <2.0.0'
dependencies:
  logging: '>=0.11.3'
  path: '>=1.3.9'
  synchronized: '>=0.1.0'

dev_dependencies:
  test: '>=0.12.5'
  dev_test: '>=0.9.3'
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
