name: sembast
version: 1.13.3+1
author: Alexandre Roux Tekartik <alex@tekartik.com>
description: NoSQL persistent embedded file system document-based database for Dart VM and Flutter with encryption support.
homepage: https://github.com/tekartik/sembast.dart
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dependencies:
  meta: '>=1.1.6 <3.0.0'
  logging: '>=0.11.3 <3.0.0'
  path: '>=1.5.1 <3.0.0'
  synchronized: '>=2.1.0 <4.0.0'

dev_dependencies:
  xxtea: '>=2.0.2'
  pedantic: '>=1.4.0'
  test: '>=1.5.1'
  dev_test: '>=0.13.0+3'
  process_run:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'
