name: sembast
version: 1.8.0
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: Simple embedded file system database
homepage: https://github.com/tekartik/sembast.dart
environment:
  sdk: '>=2.0.0-dev.49.0 <2.0.0'
dependencies:
  logging: '>=0.11.3'
  path: '>=1.3.9'
  synchronized: '>=1.5.0-dev.2'
  dart2_constant: '>=1.0.1'

dev_dependencies:
  test: '>=0.12.35'
  dev_test: '>=0.1.0'
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
  browser: any

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
