name: sembast
version: 0.4.0
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: Simple embedded file system database
homepage: https://github.com/alextekartik/sembast.dart
dependencies:
  logging: any
  path: any
dev_dependencies:
  test: any
  tekartik_test:
    git: git://github.com/alextekartik/tekartik_test.dart
dependency_overrides:
#  idb_shim:
#    path: ../idb_shim.dart
