name: sembast
version: 1.2.0
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: Simple embedded file system database
homepage: https://github.com/alextekartik/sembast.dart
dependencies:
  logging: any
  path: any
dev_dependencies:
  test: any
dependency_overrides:
  dev_test:
    path: /media/ssd/devx/git/github.com/alextekartik/dev_test.dart
#    git: https://github.com/alextekartik/dev_test.dart