name: sembast_repo
description: Sembast repo
version: 0.1.0
homepage: https://github.com/tekartik/sembast.dart
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.0+1'

dependency_overrides:
  pedantic: '>=1.4.0 <3.0.0'

