name: sembast_web
description: Sembast for the Web
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sembast: '>=2.1.3'
  idb_shim: '>=1.10.3-dev.1'

dev_dependencies:
  pedantic: '>=1.8.0'
  test: '>=1.6.0'
  process_run:
  build_runner: '>=1.5.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  webdev:

dependency_overrides:
  sembast:
    path: ../sembast
