name: sembast_web
description: NoSQL persistent embedded database for the Web on top of IndexedDB
version: 1.2.0
homepage: https://github.com/tekartik/sembast.dart/tree/master/sembast_web

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  sembast: '>=3.0.0-nullsafety.2 <4.0.0'
  idb_shim: '>=2.0.0-nullsafety.1 <3.0.0'

dev_dependencies:
  pedantic: '>=1.10.0-nullsafety.3'
  test: '>=1.16.0-nullsafety.12'
  process_run:
  build_runner: '>=1.5.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  webdev:
